services:

  postgres:
    image: postgres:14.3-alpine
    container_name: test_pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}
      - POSTGRES_ENCODING=UTF8
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
